### ISSUE TITLE
The extension seems to have stopped working on Indeed.com

### ISSUE THREAD

**Issue by justinfarrelldev** [CalvinWu4/inDoors#11]
For a little while, it worked flawlessly. The past few days though, it doesn't work on Indeed. There is this error in the console: 
```
indeed.js:5 Uncaught ReferenceError: appendGlassdoor is not defined
    at indeed.js:5:9
    at Array.forEach (<anonymous>)
    at indeed.js:3:6
```

I am running Chromium (latest) on Lubuntu (latest). I tried both with and without uBlock Origin but the result is the same. 

Thank you!

**Comment by CalvinWu4** [comment]
Hmm I still see it working in Indeed on Chrome
Can you give me the exact repro steps?

**Comment by CalvinWu4** [comment]
This has been fixed in the latest version
