### ISSUE TITLE
Not working on linkedIn

### ISSUE THREAD

**Issue by morenoh149** [CalvinWu4/inDoors#12]
Doesn't seem to work on this job page. Am I missing something?

<img width="1180" alt="Screen Shot 2022-12-07 at 11 24 32 AM" src="https://user-images.githubusercontent.com/587438/206234494-17ec9369-0ab8-4d34-a504-81cd2bb52caf.png">

**Comment by CalvinWu4** [comment]
It works for me on Firefox
Are you still having the issue?

**Comment by morenoh149** [comment]
seems to work on a different computer 

<img width="531" alt="Screen Shot 2023-01-17 at 11 17 23 AM" src="https://user-images.githubusercontent.com/587438/212954815-2a5e8ad6-9ad6-4f7d-92c5-bb8748fc5601.png">
