### ISSUE TITLE
[Request] redirect to appropriate country specific glassdoor site

### ISSUE THREAD

**Issue by piyu-sh** [CalvinWu4/inDoors#13]
Currently if you click on glassdoor reviews link that comes under company name, it takes you to glassdoor.com/company-url but can it be changed to auto redirect to region specific site, e.g. glassdoor.co.in ?
![image](https://user-images.githubusercontent.com/7107647/217315011-a5cdc9ed-9715-41a8-9eed-c152c4cae3dc.png)

**Comment by CalvinWu4** [comment]
I'll look into redirecting based on IP address region
I see that you're also using LinkedIn in dark mode? I'm thinking you would also appreciate adding dark mode support as well?

**Comment by piyu-sh** [comment]
@CalvinWu4 thanks for acknowledging the request !
And you have observant eyes 😄 imo dark mode isn't a necessity as its working fine through another extension, but surely a good to have.

**Comment by CalvinWu4** [comment]
Dark mode support has been added
However, I don't think I will add support for redirecting based on IP address region since the ratings on my extension come from glassdoor.com and glassdoor.co.in has different ratings

**Comment by piyu-sh** [comment]
Ohh cool, but how does this dark mode support activate ?
It looks the same to me 
![image](https://github.com/CalvinWu4/inDoors/assets/7107647/63afc64b-d1de-4e21-a999-188852becc47)


Also no worries about the redirecting thing, I made it work via the modheader extension

**Comment by CalvinWu4** [comment]
It works with the built in LinkedIn dark mode
