### ISSUE TITLE
Feature request: glassdoor ratings on "my jobs" page

### ISSUE THREAD

**Issue by nomino3390** [CalvinWu4/inDoors#15]
Of indeed. This one: https://myjobs.indeed.com/saved

Currently, on this page, you have to click on the job listing, and then click on the company in order to see their glassdoor rating. It'd be nice to have glassdoor ratings on the separate job listing page too- https://www.indeed.com/viewjob?*

Thanks for the awesome extension!

**Comment by nomino3390** [comment]
Updated the empty first post.

**Comment by CalvinWu4** [comment]
Will look into fixing extension on Indeed since it completely changed its UI

**Comment by CalvinWu4** [comment]
This has been solved in the latest version
